### ISSUE TITLE
Configure Keycloack in a context path not in its own domain

### ISSUE THREAD

**Issue by imartinezortiz** [e-ucm/simva-infra#23]
Currently, different domains are required for the different components. One of the blockers was KC, but seems that it is possible to configure in a context path
- https://www.keycloak.org/server/hostname
- https://github.com/keycloak/keycloak/discussions/11546
  - https://github.com/keycloak/keycloak/ issues/10321

**Comment by jujusb** [comment]
done during the keycloak upgrade
