### ISSUE TITLE
Add also clients uadventure and conectado into keycloak

### ISSUE THREAD

**Issue by Synpheros** [e-ucm/simva-infra#7]
They have to be copied from sso.simva.e-ucm.es and added into the automated creation script.

**Comment by imartinezortiz** [comment]
We need to figure it out how to install new clients not to add them by default.

  There was an open issue regarding [KEYCLOAK-14595](https://issues.redhat.com/browse/KEYCLOAK-14595), but although there is no movement in the issue, keycloak 11 already updates the library that I mentioned, so I need check if now it's possible to add new clients with the admin client. This way, we can document how to add new clients.

**Comment by jujusb** [comment]
already done with the keycloak upgrade
